---
title: Program
author: Tatjana Kecojevic
date: '2020-01-09'
slug: program
categories: []
tags:
  - wids
  - ds
  - data science
comments: yes
image: ''
menu: ''
share: yes
---
On the **22nd of April, 2020** Subotica is joining the international conference [WiDS](https://www.widsconference.org). The [Women in Data Science (WiDS)](https://www.widsconference.org) initiative aims to inspire and educate data scientists worldwide, regardless of gender, and support women in the field. WiDS started as a conference at Stanford in November 2015. Now, WiDS includes a global conference, with 150+ regional events worldwide including a [datathon](https://www.widsconference.org/datathon.html) (encouraging participants to hone their skills) and a [podcast](https://www.widsconference.org/podcast.html) (featuring leaders in the field talking about their work, and their journeys). 

Our program contains a talks and workshops by data scientists and a panel discussion with women in data science focusing mainly on diversity and mentorship. 

#### The event is free, but registration is required by ...[link to a google form?]()

#### DETAILED programe is coming soon.

###

### Speakers

- **[Tijana Blagojev](https://www.linkedin.com/in/tijana-blagojev-288b3442/)**: "title and abstract"

Tijana holds a Master’s degree in Politics, Big Data and Quantitative Methods from the [University of Warwick](https://warwick.ac.uk). She is also a recipient of renowned [Chevening](https://www.chevening.org) scholarship that provided her with the opportunity to study in the UK. She absolutely loves R and wants to share her knowledge with people and students in Serbia. She is a coorganiser of [R-ladies Belgrade](https://www.meetup.com/rladies-belgrade/) chapter. 

- **[Bojana Soro](https://www.linkedin.com/in/bojana-soro-73ba65131/)**: "title and abstract"

Bojana... bio

- **[Jovana Savić](https://www.linkedin.com/in/jovana-savić-12aa305a/)**: "title and abstract"

Jovana... bio



### Workshops

- **[Jelena Joksimović](https://www.linkedin.com/in/jelenajoksimovic92/)**: "title and abstract"

Jelena... bio

- **[Olivera Grljević](https://www.linkedin.com/in/olivera-grljević-3842b516/)**: "title and abstract"

Olivera... bio


### Panel Discussion: Shifting the gender balance in STEM


##### moderator: **[Katarina Kosmina](https://www.linkedin.com/in/kosmina/)** ... bio

##### Panelists:

- R-Ladies BG

- R-Ladies NS

- R-Ladies NI

- R-Ladies KG

- WiDS HR


